_wandb:
    value:
        cli_version: 0.22.3
        e:
            q19vmya0i5azdcbbirgpgzlbphr09xyv:
                codePath: bot.py
                codePathLocal: bot.py
                cpu_count: 6
                cpu_count_logical: 6
                disk:
                    /:
                        total: "1000186310656"
                        used: "794250625024"
                email: cuteslenaa@gmail.com
                executable: C:\Users\cutes\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe
                host: 3FBTS4CR
                memory:
                    total: "17122422784"
                os: Windows-10-10.0.26100-SP0
                program: E:\rl AI\bot.py
                python: CPython 3.11.9
                root: E:\rl AI
                startedAt: "2025-11-10T20:50:16.035260Z"
                writerId: q19vmya0i5azdcbbirgpgzlbphr09xyv
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.9
            "5": 0.22.3
            "8":
                - 3
            "10":
                - 20
            "12": 0.22.3
            "13": windows-amd64
critic_layer_sizes:
    value:
        - 256
        - 256
        - 256
critic_lr:
    value: 0.0001
exp_buffer_size:
    value: 150000
gae_gamma:
    value: 0.99
gae_lambda:
    value: 0.95
min_inference_size:
    value: 7
n_proc:
    value: 8
policy_layer_sizes:
    value:
        - 256
        - 256
        - 256
policy_lr:
    value: 0.0001
ppo_batch_size:
    value: 50000
ppo_clip_range:
    value: 0.2
ppo_ent_coef:
    value: 0.01
ppo_epochs:
    value: 2
ppo_minibatch_size:
    value: 50000
shm_buffer_size:
    value: 8192
standardize_obs:
    value: true
standardize_returns:
    value: true
timestep_limit:
    value: 200000000
ts_per_iteration:
    value: 50000
